### ISSUE TITLE
Error in home

### ISSUE THREAD

**Issue by ilsitodeiperche** [Codeinwp/oria#14]
Hello! I have an issue in homepage after the update of worpress. The articles are not see in form of grid, but in form of list. Why? Thank you. (This is my site to see the problem: http://samusgamesmemories.adreamerswayfaring.com/)

**Comment by rodica-andronache** [comment]
Hi @ilsitodeiperche ,

Thank you for reporting this issue to us. We just released an update to fix this. Let us know if everything is ok now.

Regards,
Rodica

**Comment by ilsitodeiperche** [comment]
Thank you! Everything is ok now!
