### ISSUE TITLE
Remove the header title and description

### ISSUE THREAD

**Issue by renancmfreitas** [Codeinwp/oria#16]
Hi,

If someone wants to remove the header Title and Description of the Oria, just change the style.css theme file, adding "display: none;":

.site-title {
    font-size: 62px;
    display: table;
    margin: 0 auto;
    padding: 15px;
    font-weight: 700;
    display: none;
}
.site-description {
    display: table;
    font-size: 18px;
    color: #bbb;
    margin: 15px auto 0;
    padding: 15px 15px 0;
    border-top: 1px solid rgba(255, 255, 255, 0.2);
    display: none;

**Comment by rodica-andronache** [comment]
Hi @renancmfreitas ,

Thanks for sharing your solution :) As a suggestion we usually don't recommend changing the themes files, but rather using a child theme to not loose the changes on a theme update.
Anyway, we use github for issues management, and I will need to close this. If you want to have this message visible to the users, you can always post on the wordpress.org forum.

Thank you again,
Rodica
