### ISSUE TITLE
Photo don't charge

### ISSUE THREAD

**Issue by dootaa** [Codeinwp/oria#17]
Hi everywhone,

I'm new using Oria theme on my wordpress site.
I have problem that I can't resolve. 
I can not put the image on my post in the way that it would show in the carousel on the homepage.

Can any one help?..

sorry for my english

Dorota

**Comment by rodica-andronache** [comment]
Hi Dorota,

Thank you for contacting us. I don't really understand the issue. Could you please give us more details and your site URL so I can see the issue?

Regards,
Rodica

**Comment by rodica-andronache** [comment]
Hi Dorota,

I will close this issue as we didn't receive any answer, but if you still have issues please let us know here http://themeisle.com/contact/

Regards,
Rodica
