### ISSUE TITLE
Carousel 

### ISSUE THREAD

**Issue by Meru125** [Codeinwp/oria#21]
Hi,

I've recently started using oria, but I am not experienced with programming. I have a question about the carousel function. Users of our site have complained about the fact that the carousel changes the height based on the image that is used for the post. My question is if there is a way to set a fixed height that simply doesn't change or is it easier to only use images that don't stretch the carousel?

**Comment by rodica-andronache** [comment]
Hi,

The easiest way would be to use same height images. The other alternative would be to use some CSS to make the slider of a certain height but this requires some coding knowledge and it will also not keep the image's sizes.

Regards.
Rodica

**Comment by anshgyl** [comment]
I set all the featured images to the same dimensions and also added the following code to the custom CSS
```
.item-sizer {
	height: 546px;
}
```
Still the spacing between the carousel or article previews remains unequal and the website looks very unsymmetrical.
