### ISSUE TITLE
Cannot remove right side bar

### ISSUE THREAD

**Issue by whitecat** [Codeinwp/oria#31]
I want no right side bar I cannot remove it from the theme.

**Comment by whitecat** [comment]
Why was this closed? Is there a way to remove the right side bar from the theme?

**Comment by rodica-andronache** [comment]
Hi,

There is not an option in the theme, to allow you to remove the sidebar, unless you do some custom work. You can just remove all the widgets from the sidebar and add .content-area { width: 100% !important; } in Appearance > Customize > Additional CSS
