### ISSUE TITLE
Sidebar in responsive mode

### ISSUE THREAD

**Issue by djinlemage** [Codeinwp/oria#36]
Hello, 

Thank you for your work, it's great. 

I encounter a concern:
In responsive mode, the sidebar is hidden by the menu bar.
Here are 2 impressions of screen so you can see the problem.

![mode ko](https://user-images.githubusercontent.com/15437257/30828483-161d080a-a23e-11e7-80cc-94f637cff001.png)
![mode ok](https://user-images.githubusercontent.com/15437257/30828482-15fd52c6-a23e-11e7-93f5-2a9d462edee6.png)

Can you tell me how to solve it?

Thanks in advance and again bravo !

**Comment by djinlemage** [comment]
Hello,

Sorry but the solution does not work : 

![sans titre](https://user-images.githubusercontent.com/15437257/41896094-ffbfb57c-7923-11e8-8d55-330cf35940ff.png)
https://image.noelshack.com/fichiers/2018/26/2/1529998350-sans-titre.png

**Comment by djinlemage** [comment]
Hello, but the solution does not work

![sans titre](https://user-images.githubusercontent.com/15437257/41896430-dd5d90b6-7924-11e8-82c5-1cbab77a39e8.png)

**Comment by stefan-cotitosu** [comment]
@djinlemage Can you please share you website URL so I can take a look?

**Comment by djinlemage** [comment]
@stefan-cotitosu Of course : miam.lpdd.fr
