### ISSUE TITLE
error in social bar icons

### ISSUE THREAD

**Issue by fzely** [Codeinwp/oria#43]
![site](https://user-images.githubusercontent.com/36541873/36314623-85639b76-131c-11e8-9e26-9ac4da299873.png)
![Uploading site.png…]()
the social bar icons only appear with the preview on the development page.

I have tested several bowsers and they all have the same error. How to correct?

**Comment by rodica-andronache** [comment]
@radu-themeisle could you please also check this? Make sure the font for the social icons is loading. And also test, and make sure you don't have that font on your computer, so it takes it from there 👍

**Comment by radu-themeisle** [comment]
@fzely I tested the theme (on several browsers) and the Social bar works fine, fonts are loaded properly. If you have the latest version can you please check that all the fonts were installed?
