### ISSUE TITLE
Missing Github Social Icon.

### ISSUE THREAD

**Issue by TheGeoLawton** [Codeinwp/oria#6]
Hi, I'm using your theme (Which I am loving) as a portfolio and blog for myself as an IT consultant. But when I tried to add my github as a social link, I noticed there was no Github icon. Can you add Github as a supported social link or give me a clue where to start to create and add my own?

**Comment by rodica-andronache** [comment]
Hi @TheGeoLawton ,

Can you please give me your site URL so I see where are you using the social icons?

Thank you,
Rodica

**Comment by TheGeoLawton** [comment]
My site is located at [http://Lawtonia.com](lawtonia.com)

**Comment by rodica-andronache** [comment]
Hi @TheGeoLawton you could create a child theme, and add this line in the style.css file:
`.social-navigation li a[href*="github.com"]::before {
	content: '\f09b';
}`
This way you could add a github icon
Regards,
Rodica

**Comment by TheGeoLawton** [comment]
Thank you for your help, your code added the icon!

**Comment by rodica-andronache** [comment]
Happy to help!
