### ISSUE TITLE
Error in translation

### ISSUE THREAD

**Issue by madvik** [Codeinwp/oria#7]
Hi,
I have a problem of translation on comments (`comments.php`)
![image](https://cloud.githubusercontent.com/assets/3822529/15745643/4409fd62-28d3-11e6-8722-693f31170471.png)
I don't understand where is the problem.
thanks

**Comment by rodica-andronache** [comment]
Hi @madvik , 
Can you please give more details about your issue? What are you using for translations?

Regards,
Rodica

**Comment by madvik** [comment]
On the screenshot, the word "thoughts" is not translate In french.
Thx
